name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: preresquites
      run: sudo apt-get install gcc coreutils
    - name: make
      run: make img
    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
          name: image
          path: atlas.img
